# Generated by Django 4.1.2 on 2022-10-18 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=180)),
                ("web_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=180)),
                ("sku", models.CharField(max_length=180)),
                ("brand", models.CharField(max_length=180)),
                ("type", models.CharField(max_length=180)),
                ("size", models.CharField(max_length=180, null=True)),
                ("image_url", models.CharField(max_length=280)),
                ("price", models.FloatField()),
                (
                    "store_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store",
                        to="store.store",
                    ),
                ),
            ],
        ),
    ]
