version: '3.8'
services:
  api:
    build: .
    volumes:
      - .:/app
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000 --timeout 0 --reload
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust # Insecure connection, internal only

volumes:
  postgres:
    driver: local

  # nginx:
  #     build: ./nginx
  #     # volumes:
  #     #     - static_volume:/home/app/web/staticfiles
  #     ports:
  #         - 80:80
  #     depends_on:
  #         - api
